FROM python:3.12-alpine

WORKDIR /app

COPY alembic.ini .
COPY alembic/ ./alembic
COPY monitox/ ./monitox/
COPY requirements.txt .

RUN pip install -r requirements.txt

CMD ["alembic", "upgrade", "head"]
