[tool.poetry]
name = "monitox"
version = "0.1.0"
description = ""
authors = ["roman.k <rvkrisanov@yandex.ru>"]
readme = "README.md"
package-mode = false
[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
