global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'bot'
    static_configs:
      - targets: ['py_prometheus:8001']
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
