"""delete created_at in query

Revision ID: 32d3eeab8551
Revises: 92a7a62bd3b6
Create Date: 2024-09-07 02:40:03.987421

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32d3eeab8551"
down_revision: Union[str, None] = "92a7a62bd3b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("query", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "query", sa.Column("created_at", sa.TEXT(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
