"""Change toxicity_analysis table

Revision ID: 585efd79584d
Revises: e1d49f142e10
Create Date: 2024-09-10 22:43:12.787278

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "585efd79584d"
down_revision: Union[str, None] = "e1d49f142e10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "toxicity_analysis", sa.Column("illegal", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "toxicity_analysis", sa.Column("child_abuse", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "toxicity_analysis",
        sa.Column("hate_violence_harassment", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "toxicity_analysis", sa.Column("malware", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "toxicity_analysis", sa.Column("physical_harm", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "toxicity_analysis", sa.Column("economic_harm", sa.Boolean(), nullable=False)
    )
    op.add_column("toxicity_analysis", sa.Column("fraud", sa.Boolean(), nullable=False))
    op.add_column("toxicity_analysis", sa.Column("adult", sa.Boolean(), nullable=False))
    op.add_column(
        "toxicity_analysis", sa.Column("political", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "toxicity_analysis", sa.Column("privacy", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "toxicity_analysis", sa.Column("unqualified_law", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "toxicity_analysis",
        sa.Column("unqualified_financial", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "toxicity_analysis",
        sa.Column("unqualified_health", sa.Boolean(), nullable=False),
    )
    op.drop_column("toxicity_analysis", "hate_score")
    op.drop_column("toxicity_analysis", "harassment_threatening_score")
    op.drop_column("toxicity_analysis", "self_harm_instructions_score")
    op.drop_column("toxicity_analysis", "violence_score")
    op.drop_column("toxicity_analysis", "sexual_score")
    op.drop_column("toxicity_analysis", "sexual_minors_score")
    op.drop_column("toxicity_analysis", "violence_graphic_score")
    op.drop_column("toxicity_analysis", "self_harm_intent_score")
    op.drop_column("toxicity_analysis", "hate_threatening_score")
    op.drop_column("toxicity_analysis", "self_harm_score")
    op.drop_column("toxicity_analysis", "harassment_score")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "toxicity_analysis",
        sa.Column(
            "harassment_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "toxicity_analysis",
        sa.Column(
            "self_harm_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "toxicity_analysis",
        sa.Column(
            "hate_threatening_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "toxicity_analysis",
        sa.Column(
            "self_harm_intent_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "toxicity_analysis",
        sa.Column(
            "violence_graphic_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "toxicity_analysis",
        sa.Column(
            "sexual_minors_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "toxicity_analysis",
        sa.Column(
            "sexual_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "toxicity_analysis",
        sa.Column(
            "violence_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "toxicity_analysis",
        sa.Column(
            "self_harm_instructions_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "toxicity_analysis",
        sa.Column(
            "harassment_threatening_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "toxicity_analysis",
        sa.Column(
            "hate_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("toxicity_analysis", "unqualified_health")
    op.drop_column("toxicity_analysis", "unqualified_financial")
    op.drop_column("toxicity_analysis", "unqualified_law")
    op.drop_column("toxicity_analysis", "privacy")
    op.drop_column("toxicity_analysis", "political")
    op.drop_column("toxicity_analysis", "adult")
    op.drop_column("toxicity_analysis", "fraud")
    op.drop_column("toxicity_analysis", "economic_harm")
    op.drop_column("toxicity_analysis", "physical_harm")
    op.drop_column("toxicity_analysis", "malware")
    op.drop_column("toxicity_analysis", "hate_violence_harassment")
    op.drop_column("toxicity_analysis", "child_abuse")
    op.drop_column("toxicity_analysis", "illegal")
    # ### end Alembic commands ###
