"""create toxicity_analysis  table

Revision ID: 92a7a62bd3b6
Revises: 5045a8630e72
Create Date: 2024-09-07 02:26:43.877679

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92a7a62bd3b6"
down_revision: Union[str, None] = "5045a8630e72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "toxicity_analysis",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("flagged", sa.Boolean(), nullable=False),
        sa.Column("sexual", sa.Boolean(), nullable=False),
        sa.Column("hate", sa.Boolean(), nullable=False),
        sa.Column("harassment", sa.Boolean(), nullable=False),
        sa.Column("self_harm", sa.Boolean(), nullable=False),
        sa.Column("sexual_minors", sa.Boolean(), nullable=False),
        sa.Column("hate_threatening", sa.Boolean(), nullable=False),
        sa.Column("violence_graphic", sa.Boolean(), nullable=False),
        sa.Column("self_harm_intent", sa.Boolean(), nullable=False),
        sa.Column("self_harm_instructions", sa.Boolean(), nullable=False),
        sa.Column("harassment_threatening", sa.Boolean(), nullable=False),
        sa.Column("violence", sa.Boolean(), nullable=False),
        sa.Column("sexual_score", sa.Float(), nullable=False),
        sa.Column("hate_score", sa.Float(), nullable=False),
        sa.Column("harassment_score", sa.Float(), nullable=False),
        sa.Column("self_harm_score", sa.Float(), nullable=False),
        sa.Column("sexual_minors_score", sa.Float(), nullable=False),
        sa.Column("hate_threatening_score", sa.Float(), nullable=False),
        sa.Column("violence_graphic_score", sa.Float(), nullable=False),
        sa.Column("self_harm_intent_score", sa.Float(), nullable=False),
        sa.Column("self_harm_instructions_score", sa.Float(), nullable=False),
        sa.Column("harassment_threatening_score", sa.Float(), nullable=False),
        sa.Column("violence_score", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("query", "toxic_probability")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "query",
        sa.Column(
            "toxic_probability",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("toxicity_analysis")
    # ### end Alembic commands ###
