"""Edit  table role

Revision ID: dd2c86317d4e
Revises: a24626d0930e
Create Date: 2024-09-08 16:05:30.215302

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd2c86317d4e"
down_revision: Union[str, None] = "a24626d0930e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "role", sa.Enum("ROLE_ADMIN", "ROLE_USER", name="user_role"), nullable=False
        ),
        sa.PrimaryKeyConstraint("user_id", "role"),
    )
    op.drop_table("role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("role", sa.TEXT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("user_id", "role", name="role_pkey"),
    )
    op.drop_table("users")
    # ### end Alembic commands ###
